### ISSUE TITLE
Improve docker-compose.yml-example in README.md to work out of the box

### ISSUE THREAD

**Issue by drjackyl** [cj123/assetto-server-manager#164]
Hi,

CptJackZ here from the racedepartment support thread. I struggled the whole evening to get a server up and running and finding it in the lobby. After a couple of hours, searching and fiddeling with docker, ufw, iptables, nmap and nc, I found the issue: I took the docker-compose.yml-example and it is insufficient, since it does not publish 9600/udp. As an effect, the registration with the central server failed with the error response: "ERROR,INVALID SERVER,CHECK YOUR PORT FORWARDING SETTINGS".

So I suggest to change the docker-compose.yml-example in the README.md, so it can work copy/paste:

```YAML
version: "3"

services:
  server-manager:
    image: seejy/assetto-server-manager:latest
    ports:
    # the port that the server manager runs on
    - "8772:8772"
    # the port that the assetto server runs on (may vary depending on your configuration inside server manager)
    - "9600:9600"
    - "9600:9600/udp"
    # the port that the assetto server HTTP API runs on.
    - "8081:8081"
    # you may also wish to bind your configured UDP plugin ports here. 
    volumes: 
    # volume mount the entire server install so that 
    # content etc persists across restarts
    - ./server-install:/home/assetto/server-manager/assetto
    
    # volume mount the config
    - ./config.yml:/home/assetto/server-manager/config.yml
```

AFAIK, the HTTP-port doesn't need UDP.

The port-forwardings should also be strings (wrapped in quotes), according to the documentation: https://docs.docker.com/compose/compose-file/#ports

> For this reason, we recommend always explicitly specifying your port mappings as strings.

Hopefully, I can now really try out this great tool ;-)

Regards
